# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  # Specify folders explicitly to avoid running on `commands`, which is a symlink to `src/commands`
  - id: lint_format
    name: Linting and formatting
    stages: [pre-commit]
    language: system
    entry: bash -lc "uv run delfino ruff"
    pass_filenames: false
